# Generated by Django 3.2.2 on 2021-06-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myForumApp', '0005_forumuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumuser',
            name='name',
        ),
    ]
