# Generated by Django 3.2.2 on 2021-06-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForumApp', '0006_remove_forumuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forumuser',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
