# Generated by Django 3.2.2 on 2021-07-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForumApp', '0007_auto_20210628_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
