# Generated by Django 3.2.2 on 2021-07-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForumApp', '0008_alter_forumuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
